### ISSUE TITLE
某些设备上的某些资源播放器有画面没声音

### ISSUE THREAD

**Issue by Jackie2co** [AttemptD/AfuseKtV-release#11]
我用的是极米投影仪，安装的电视版软件，很多音轨为AC3的资源会出现播放的时候有画面没声音

**Comment by AttemptD** [comment]
出现有画面没声音的情况，在播放界面左下角有四个按钮，第四个ffmpeg打开即可

**Comment by Jackie2co** [comment]
第四个按钮里只有默认音轨和disable，但是我在播放设置找到了这个选项，并打开了ffmpeg，但还是没有声音，软件里的三种播放器都试过了，都没声音。但是又很奇怪，我换成我家的另一台电视机的设备，是有声音的

**Comment by AttemptD** [comment]
exo本身就是跟设备走，解码依靠硬件，如果开启ffmpeg，都不行，说明你的tv连ffmpeg都无法应用上发自我的 iPhone在 2024年11月16日，21:53，Jackie2co ***@***.***> 写道：﻿
第四个按钮里只有默认音轨和disable，但是我在播放设置找到了这个选项，并打开了ffmpeg，但还是没有声音，软件里的三种播放器都试过了，都没声音。但是又很奇怪，我换成我家的另一台电视机的设备，是有声音的
