### ISSUE TITLE
雷鸟（TCL）65S535D无法添加资源库

### ISSUE THREAD

**Issue by Yee-Joe** [AttemptD/AfuseKtV-release#2]
在pad上面用Afusekt很好用，可以正常添加webdav使用，但是在电视上，从1.3.4-10086版本开始安装到现在10091版本，有的时候安装后找不到APP的图标，有的版本可以打开软件，但是每一个版本都没有添加资源库的按钮，在PAD上是有“+”按钮可以添加webdav的，点击获取资源库显示没有权限，求大佬关注一下，感恩~~
![1723444551703](https://github.com/user-attachments/assets/77a73f10-7acf-45da-8425-9470861f701c)
电视信息，系统是安卓9.0。软件安装V7的可以安装上去

**Comment by AttemptD** [comment]
tv需要订阅永久pro才可同步发自我的 iPhone在 2024年8月12日，14:37，Yee-Joe ***@***.***> 写道：﻿
在pad上面用Afusekt很好用，可以正常添加webdav使用，但是在电视上，从1.3.4-10086版本开始安装到现在10091版本，有的时候安装后找不到APP的图标，有的版本可以打开软件，但是每一个版本都没有添加资源库的按钮，在PAD上是有“+”按钮可以添加webdav的，点击获取资源库显示没有权限，求大佬关注一下，感恩~~
1723444551703.png (view on web)
电视信息，系统是安卓9.0。软件安装V7的可以安装上去
