### ISSUE TITLE
TV版本能不添加本地的移动硬盘资源

### ISSUE THREAD

**Issue by JackyCBN** [AttemptD/AfuseKtV-release#3]
已经购买永久版，但是想在TV版直接使用移动硬盘资源，
要怎么操作

**Comment by AttemptD** [comment]
tv版本暂时还无法添加本地，后续可能会有此功能上新，目前的计划暂时还未考虑，很抱歉发自我的 iPhone在 2024年8月24日，12:58，JackyCBN ***@***.***> 写道：﻿
已经购买永久版，但是想在TV版直接使用移动硬盘资源，
要怎么操作
