### ISSUE TITLE
vidda播放mpv和vlc闪退，只有exo正常播放

### ISSUE THREAD

**Issue by zero617** [AttemptD/AfuseKtV-release#6]

**Comment by zero617** [comment]
软件版本：AfusektV-armeabi-v7a-release_1.3.6-10105-fix

**Comment by AttemptD** [comment]
目前tv最佳解决方案就是exo，其他两个并不合适，android tv盒子芯片普遍落后发自我的 iPhone在 2024年9月6日，08:59，zero617 ***@***.***> 写道：﻿
软件版本：AfusektV-armeabi-v7a-release_1.3.6-10105-fix
