### ISSUE TITLE
bug上报

### ISSUE THREAD

**Issue by QianYushi** [AttemptD/AfuseKtV-release#7]
1、smb连接服务器，资源库载入到一半显示无法连接，无权限
2、折叠屏大屏模式下，点击播放按钮没有用（使用外屏可以）
![Screenshot_20240930_193651](https://github.com/user-attachments/assets/07e65e67-aa31-457d-a003-28c3b848a2fb)
![Screenshot_20240930_193718](https://github.com/user-attachments/assets/40879b79-ff5b-4a33-8a3e-2404058839a7)

**Comment by AttemptD** [comment]
这是TV项目
